steps:
  - name: 'gcr.io/kaniko-project/executor'
    args:
      - --dockerfile=Dockerfile
      - --context=dir://.
      - --destination=gcr.io/$PROJECT_ID/strikers-app
      - --cache=true
options:
  logging: CLOUD_LOGGING_ONLY