steps:
  # The new way to build: faster and more reliable
  - name: 'gcr.io/kaniko-project/executor'
    args:
      - --destination=gcr.io/$PROJECT_ID/strikers-app
      - --cache=true
      - --cache-ttl=24h
options:
  logging: CLOUD_LOGGING_ONLY